---
- name: trac
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    - { role: mysql, tags: mysql }
    - { role: trac, tags: trac }