- name: Trac
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt update && sudo apt-get -y install python'

- name: Trac
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    - { role: mysql, tags: mysql }
    - { role: trac, tags: trac }
